remote_theme: just-the-docs/just-the-docs@v0.4.0.rc4

plugins:
  - jekyll-seo-tag

title: "Yumekko Strat"
description: "Yumekko Private Strat"

favicon_ico: "favicon.ico"

color_scheme: light

aux_links:
  "Yumekko Discord(非対応）":
    - ""

aux_links_new_tab: true

enable_copy_code_button: true

back_to_top: true
back_to_top_text: "Back to top"
